### ISSUE TITLE
Printing individual time breakup values for the Simulator

### ISSUE THREAD

**Issue by NikPrav** [stonne-simulator/stonne#30]
Inside STONNEModel.cpp, from line numbers 542 to 547, to print individual values, the current object is not referenced. Is that by design? The benchmarked time values are stored in the variables associated to that object before. See code snippet below

`std::cout << "Time mem(ms): " << time_mem << std::endl;`

As opposed to 

`std::cout << "Time mem(ms): " << this->time_mem << std::endl;`

**Comment by Adrian-2105** [comment]
Hi! As `Stonne::cycle()` is a class method of `Stonne`, class attributes are referenced implicitly without using `this`. Thus, the code is correct but wasn't programmed using strict naming guidelines.

**Comment by Adrian-2105** [comment]
Actually, these values do not give any information about the simulated operation in the architecture. They are just execution time counters, in seconds. The result appears as 0 because it is converted from microseconds to seconds ([see this](https://github.com/stonne-simulator/stonne/blob/633fa5322e4976c377b14b2d717f3f2adcd8aa51/stonne/src/STONNEModel.cpp#L543)), without decimals.

This is a programming error, but as I said this is not important and that output could be deleted from the simulator
