### ISSUE TITLE
Can i change  stonne  for our own accelerator architecture

### ISSUE THREAD

**Issue by mig9mili** [stonne-simulator/stonne#31]
So far i understood  that  the stonne simulator works for MAERI and SIGMA  accelerator  , so can I change the stonne for our now accelerator architecture  to check,

**Comment by Adrian-2105** [comment]
Hi. This project is open-source. You're welcome to do a fork, modify it and use it in your research. Please cite us in that case.

**Comment by mig9mili** [comment]
hey i am  beginner  to his field and i have gone through your  yt videos it was nice  , so can you please help me out  how to go through the  your code base  basically i need a road-map so that i can understand how  marie  is implemented  on top of that i can  build my accelerator

**Comment by Adrian-2105** [comment]
I have attached the STONNE paper to this comment, so firstly I would recommend reading it: [STONNE_Enabling_Cycle-Level_Microarchitectural_Simulation_for_DNN_Inference_Accelerators.pdf](https://github.com/stonne-simulator/stonne/files/14865383/STONNE_Enabling_Cycle-Level_Microarchitectural_Simulation_for_DNN_Inference_Accelerators.pdf)

I can also give you some upper-level introduction to the simulator source code, but you will need to spend time to understand and be able to work with it. The main file structure to simulate the MAERI architecture is:

- `main.cpp`: CLI input parsing
- `STONNEmodel.cpp`: main STONNE module where all the on-chip networks are created and configured
- `SDMemory.cpp`: memory controller of MAERI, the most important component since it orchestrates the data movement and execution
- `DSNetwork.cpp` & `DSNetworkTop.cpp`: distribution network
- `MSNetwork.cpp`: multiplier network
- `ASNetwork.cpp`: reduction network

The rest of the files mainly focus on the simulation of other kinds of architecture, so you can only focus on the ones I mentioned. To get a deeper understanding of each part, you will need to navigate through the code.

**Comment by mig9mili** [comment]
thanks a lot man
