### ISSUE TITLE
STT-RAM Implementation 

### ISSUE THREAD

**Issue by meve01** [stonne-simulator/stonne#7]
Hi, I plan on implementing part of the STONNE framework but was wondering how feasible it would be to implement an emerging non-volatile memory technology such as STT-RAM. This would replace the SDMemory module and we would hope to track the behavior/performance of the memory technology on the python frontend module. Any advice as to how one could patch in a similar piece of software would be great.

Thank you, Michael

**Comment by francisco-munoz** [comment]
Hi @meve01 , 

I think connecting the simulator to STT-RAM is feasible, but you will require to perform some changes. 

I have another version of the simulator which will push soon, and it will include the connection with DRAMSimv3. However, if you want to incorporate your own connection with STT-RAM this is what you should do, depending on the scenario you want to model:

1. If you plan to implement an explicit decoupled memory hierarchy you will need to change quite a lot the module SDMemory. Here, you will have to separate these two modules into two: A first module will control the accesses to the DRAM and will feed the SRAM. Another one, will feed the multipliers based on the data in the SRAM. You could use a double buffer scheme. Eventtually, your model will connect with your non-volalite technology in DRAM. This scheme is quite complicated because it requires to synchronize both controllers to feed both the SRAM and the multipliers. 
2. If your plan is to use an implicit memory hierarchy then it is easier. You will have to create your memory hierarchy model based on cache for example, having again your STT-RAM technology in the back-end. Here, the only thing you will have to do is to send the memory requests in SDMemory.cpp to the cache, and modify slightly the controller to manage the memory requests. 

If you decide to go for it and need help, please let me know it. Also, do not hesitate to email me if you prefer so. This is my email: francisco.munoz2@um.es

**Comment by meve01** [comment]
I think our goal would be to use an implicit architecture that we'd make an STT-RAM.cpp and .h files for. This would use the second approach based on your response. I have the architectural model already done for STT-RAM but it exists in an NVSim simulator right now, so it will mainly be a matter of re-configuring that code to work with the STONNE simulator. My email is meve01@tufts.edu and I will reach out to you soon if you're able to help me out at some point :).

Thanks again, Francisco!
