### ISSUE TITLE
The unit of data and frequency of the stonne

### ISSUE THREAD

**Issue by ashsw** [stonne-simulator/stonne#8]
Hi Francisco,

I hope you are doing well.

Sorry to bother you again, but I found the data in the output file doesn't have the unit. Do you mind telling me the units of these values, such as energy, area in the output file? 

Besides, I cannot find the whole execution time for the whole operation(It just tells me how many cycles when "running a convolution layer"), nor the frequency. If there is a default frequency, could you please tell me?

Can you tell me the data size it reads from the GlobalBuffer. Should it be 8bits? or 32bits? or 64bits?

BEST
Yile

**Comment by francisco-munoz** [comment]
Hi @ashsw ,

not a bother at all. Let me ask your questions:

1. In order to get the energy and area values from the execution you need to run the script "calculate_energy" feeding it with the output of the simulation (i.e., the counter files) and your counter table. Take a look at the README in the repo, which contains a section called "generating energy numbers". There, you can see how to exactly use the script and how to generate those numbers from a particular simulation.
2. Actually, STONNE just tells you the number of simulated cycles it has taken to complete your execution. For your execution time, you can assume any frequency and calculate the time based on time = number of cycles / frequency.  Obviously, if you reduce the frequency, your energy numbers might differ and probably you will need to update the energy and area counters. To do so, you can look up papers out there or synthesize your own numbers.  Currently, the frequency used in the energy and area counters in the table of STONNE (the table shown in the README file) are for an architecture synthesized at 200 MHz. 
3. Currently the global buffer reads data width of 32 bits. However, since the version in the repository contains an unlimited GB this is actually irrelevant. You can assume any data width if you feed the energy tables with the proper numbers. In the next update, It will include the whole memory hierarchy, and here there is a parameter to select the data width.

Hope it helps

**Comment by ashsw** [comment]
Hi Francisco,

Thank you for your reply! For the first question, actually, I have done the process according to your "generating energy numbers". The output file I got has information like "GlobalBuffer: STATIC=208.7064 AREA=115029.0 DYNAMIC=1905.5520000000001". It is great! But I don't know the unit of the data. For instance, I cannot figure out STATIC=208.7064mJ? or STATIC=208.7064uJ? 

Thanks
Yile

**Comment by francisco-munoz** [comment]
Hi @ashsw , 

The numbers in the file are in uJ, as that was the unit reported by the synthesis tool

**Comment by ashsw** [comment]
Hi @francisco-munoz,

Thank you for your patience! I guess the unit for "AREA=115029.0" must be mm^2? Forgive me, just for checking. The paper about "MAERI" sets up the Prefetch Buffer=80KB and area=6mm^2. Since the area of Prefetch Buffer is fixed in Stonne, what is its total size in KB?

Thanks
Yile

**Comment by francisco-munoz** [comment]
Hi @ashsw , 

the numbers shown are for a 108 KB buffer size. And yes, if I do not remember bad, the numbers are in mm2. I might be wrong. Please let me know if that does not make sense and I will make a deep search. I do not have the results on hand now and can't look them up.

**Comment by ashsw** [comment]
Hi @francisco-munoz,

Thank you very much! I really appreciate it!
