### ISSUE TITLE
PyTorch frontend

### ISSUE THREAD

**Issue by AndreasKaratzas** [stonne-simulator/stonne#9]
Hello, I have 2 questions:

1. What is the version of PyTorch frontend that you have included in the repository? [v1.7.0 or v.17.1]
2. Could you provide a file list with the customizations you made in PyTorch? I ran `diff` using both PyTorch v1.7.0 and v1.7.1 but I couldn't get the result I was looking for. It seems that almost all files were changed.

**Comment by francisco-munoz** [comment]
Hi @AndreasKaratzas , 

thanks for reaching out. 
1. The version is 1.7.0 
2. Many of the files are generating in the compilation phase so that's probably the reason you are getting many differences. The changes required to add the SimulatedConv operation are basically these:
       -  I created the corresponding c++ function connecting STONNE simulator in the folder stonne_connection. This creates a package pytorch_stonne with the function accessible from pytorch. 
       - Once I have this, in order to create the SimulatedConv operation inside the nn package you just have to go to torch/nn/modules and create the file SimulatedConv.py which is a copy of conv.py but modifying the back-end of the conv operation with the function inside pytorch_stonne. 
       - You also have to include the SimulatedConv.py in the file "__init__.py" from the same folder. 
       - The same is valid for the linear and the rest of the operations.
I hope this helps,
Francisco.
